receive c:\reinhard\siemens\mf90ev.for       mf90ev.fort   ascii crlf
receive c:\reinhard\siemens\mf90l0.for       mf90l0.fort   ascii crlf
receive c:\reinhard\siemens\od3bif.for       od3bif.fort   ascii crlf
receive c:\reinhard\siemens\od3ev9.for       od3ev9.fort   ascii crlf
receive c:\reinhard\siemens\pic2v.for        pic2v.fort    ascii crlf
receive c:\reinhard\siemens\pic2v.cls        pic2v.clist   ascii crlf
receive c:\reinhard\siemens\prob3d.for       prob3d.fort   ascii crlf
receive c:\reinhard\siemens\clebsch.for      clebsch.fort  ascii crlf
receive c:\reinhard\siemens\gauss.for        gauss.fort    ascii crlf
receive c:\reinhard\siemens\lorattr.for      lorattr.fort  ascii crlf
receive c:\reinhard\siemens\soliton.for      soliton.fort  ascii crlf
receive c:\reinhard\siemens\soliton.cls      soliton.clist ascii crlf
