echo off
c:
cd \liermann\siemens\oberfd
s:\sna\sna_recv c:oberd2.for   oberfd.fort(oberd2)      ascii crlf
s:\sna\sna_recv c:oberd3.for   oberfd.fort(oberd3)      ascii crlf
s:\sna\sna_recv c:probd2.for   oberfd.fort(probd2)      ascii crlf
s:\sna\sna_recv c:probd3.for   oberfd.fort(probd3)      ascii crlf
s:\sna\sna_recv c:ogie2.for   oberfd.fort(ogie2)      ascii crlf
s:\sna\sna_recv c:pic1.for   oberfd.fort(pic1)      ascii crlf
:end
